import { ArrowUpRight, ChevronRight, CircleDollarSign, Target, TrendingUp, Users, Sparkles, Activity, CalendarDays } from "lucide-react";
import { Link } from "react-router-dom";
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from "recharts";
import { Card, StatCard, SectionHeader, Button, Badge, Avatar, ProgressBar } from "@/components/ui";
import { mockAIInsights, mockLeads, mockMembers, mockRevenue, mockTeams, stageColors, stageOrder } from "@/data/mockData";
import { formatCurrency, formatNumber } from "@/lib/utils";
import { useAuth } from "@/context/AuthContext";
import { useFetch } from "@/hooks/useFetch";
import { api } from "@/services/api";
import type { Team, Lead } from "@/types";

function ChartTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ value: number; name: string; color?: string }>; label?: string }) { if (!active || !payload?.length) return null; return <div className="custom-tooltip"><div className="custom-tooltip-label">{label}</div>{payload.map(p => <div className="custom-tooltip-value" key={p.name} style={{ color: p.color }}>{p.name}: {formatCurrency(p.value)}</div>)}</div>; }

export function AdminDashboard() {
  const { data: teams, loading, refetch } = useFetch<Team[]>(() => api.teams.list(), []);
  const totalRevenue = (teams ?? mockTeams).reduce((s, t) => s + t.revenue, 0);
  const totalLeads = (teams ?? mockTeams).reduce((s, t) => s + t.leadCount, 0);
  if (loading) return <><PageIntro eyebrow="Monday, August 19, 2026" title="Good morning, Avery" description="Here's what's happening across Meridian today." /><Card><div className="loading-state"><div className="skeleton loading-row" /><div className="skeleton loading-row" /><div className="skeleton loading-row" /></div></Card></>;
  if (!teams) return <Card><div className="error-state"><p>We couldn't load the organization overview.</p><Button onClick={refetch}>Try again</Button></div></Card>;
  return <>
    <PageIntro eyebrow="Monday, August 19, 2026" title="Good morning, Avery" description="Here's what's happening across Meridian today." actions={<><Button variant="outline"><CalendarDays size={15} /> This month <ChevronRight size={13} /></Button><Button variant="gold"><ArrowUpRight size={15} /> Export overview</Button></>} />
    <div className="dashboard-grid">
      <StatCard label="Total revenue" value={formatCurrency(totalRevenue)} change="+14.8%" icon={<CircleDollarSign size={15} />} accent="teal" />
      <StatCard label="Active leads" value={formatNumber(totalLeads)} change="+8.2%" icon={<Target size={15} />} accent="gold" />
      <StatCard label="Avg. conversion" value="22.1%" change="+2.4%" icon={<TrendingUp size={15} />} accent="success" />
      <StatCard label="Team members" value="19" change="+2" changeLabel="this month" icon={<Users size={15} />} accent="dark" />
    </div>
    <div className="two-col">
      <Card className="chart-card" padding={false}><SectionHeader title="Revenue performance" description="Monthly revenue across all teams" action={<Button variant="ghost" size="sm">Last 8 months <ChevronRight size={13} /></Button>} /><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={mockRevenue} margin={{ top: 10, right: 14, left: 0, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2D8285" stopOpacity={.22}/><stop offset="95%" stopColor="#2D8285" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v => `$${v/1000}K`} width={42}/><Tooltip content={<ChartTooltip />} /><Area type="monotone" dataKey="revenue" name="Revenue" stroke="#2D8285" strokeWidth={2.5} fill="url(#revenueFill)" /></AreaChart></ResponsiveContainer></div></Card>
      <Card><SectionHeader title="Team performance" description="Revenue contribution by team" action={<Link to="/admin/organization" className="text-link">View all <ArrowUpRight size={13} /></Link>} /><div className="team-list">{teams.map(t => <TeamListItem key={t.id} team={t} />)}</div></Card>
    </div>
    <div className="two-col">
      <Card className="chart-card" padding={false}><SectionHeader title="Leads by team" description="Pipeline volume and conversion" action={<Link to="/leads" className="text-link">Open pipeline <ArrowUpRight size={13} /></Link>} /><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><BarChart data={teams} margin={{ top: 10, right: 14, left: 0, bottom: 0 }} barGap={10}><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="name" tickFormatter={v => v.replace("Team ", "")} axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip content={<ChartTooltip />} /><Bar dataKey="leadCount" name="Leads" radius={[5,5,0,0]} fill="#D9A62E" /></BarChart></ResponsiveContainer></div></Card>
      <Card><SectionHeader title="Latest activity" action={<Button variant="ghost" size="sm">View all</Button>} /><div className="activity-list">{mockMembers.slice(0, 4).map((m, i) => <div className="activity-item" key={m.id}><Avatar initials={m.avatarInitials} size="sm" color={i % 2 ? "gold" : "teal"}/><div className="activity-content"><strong>{m.name}</strong> closed a deal worth <strong>{formatCurrency(m.revenue)}</strong><span className="activity-time">{i + 1} hour{i ? "s" : ""} ago · {mockTeams.find(t => t.id === m.teamId)?.name}</span></div></div>)}</div></Card>
    </div>
  </>;
}

export function TeamDashboard() {
  const { user } = useAuth(); const team = mockTeams.find(t => t.id === user?.teamId) ?? mockTeams[0];
  const leads = mockLeads.filter(l => l.teamId === team.id); const members = mockMembers.filter(m => m.teamId === team.id);
  const pipeline = stageOrder.slice(0, 6).map(stage => ({ stage, count: leads.filter(l => l.stage === stage).length }));
  return <>
    <PageIntro eyebrow={`${team.name} · Team workspace`} title={`Welcome, ${user?.name.split(" ")[0]}`} description="Your team's performance at a glance. Keep the momentum going." actions={<Button variant="gold"><ArrowUpRight size={15}/> Share report</Button>} />
    <div className="dashboard-grid"><StatCard label="Team revenue" value={formatCurrency(team.revenue)} change={`${team.growth > 0 ? "+" : ""}${team.growth}%`} icon={<CircleDollarSign size={15}/>} accent="teal" trend={team.growth > 0 ? "up" : "down"}/><StatCard label="Active leads" value={formatNumber(team.leadCount)} change="+6 this week" icon={<Target size={15}/>} accent="gold"/><StatCard label="Conversion rate" value={`${team.conversionRate}%`} change="+1.8%" icon={<TrendingUp size={15}/>} accent="success"/><StatCard label="Team members" value={String(team.memberCount)} change="All active" icon={<Users size={15}/>} accent="dark"/></div>
    <div className="two-col"><Card className="chart-card" padding={false}><SectionHeader title="Revenue trend" description="Your team’s monthly performance" action={<Link className="text-link" to="/team/revenue">Details <ArrowUpRight size={13}/></Link>}/><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={mockRevenue} margin={{ top: 10, right: 14, left: 0, bottom: 0 }}><defs><linearGradient id="teamFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#D9A62E" stopOpacity={.24}/><stop offset="95%" stopColor="#D9A62E" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v => `$${v/1000}K`} width={42}/><Tooltip content={<ChartTooltip/>}/><Area type="monotone" dataKey="revenue" name="Revenue" stroke="#D9A62E" strokeWidth={2.5} fill="url(#teamFill)"/></AreaChart></ResponsiveContainer></div></Card><Card><SectionHeader title="Pipeline overview" action={<Link className="text-link" to="/team/leads">View leads <ArrowUpRight size={13}/></Link>}/>{pipeline.map((p,i)=><div key={p.stage} style={{ marginBottom: 14 }}><div style={{ display:"flex",justifyContent:"space-between",fontSize:11,marginBottom:6 }}><span>{p.stage}</span><strong>{p.count}</strong></div><ProgressBar value={leads.length ? (p.count/leads.length)*100 : 0} color={i > 3 ? "gold" : "teal"}/></div>)}</Card></div>
    <div className="two-col"><Card><SectionHeader title="Team activity" description="Recent updates from your teammates"/><div className="activity-list">{members.slice(0,4).map((m,i)=><div className="activity-item" key={m.id}><Avatar initials={m.avatarInitials} size="sm" color={i%2?"gold":"teal"}/><div className="activity-content"><strong>{m.name}</strong> closed a deal and added <strong>{formatCurrency(m.revenue)}</strong> to revenue<span className="activity-time">{i+1} hour{i?"s":""} ago</span></div></div>)}</div></Card><Card><SectionHeader title="Team pulse"/><div className="insight-card"><div className="insight-icon insight-opportunity"><Sparkles size={15}/></div><div className="insight-body"><div className="insight-title">Your team is on track</div><div className="insight-description">You're pacing 8% ahead of your monthly revenue target. Keep focus on the {pipeline[3]?.count ?? 0} proposals currently in progress.</div><div className="insight-footer"><Badge variant="success">On track</Badge><span className="insight-metric">+8% vs target</span></div></div></div></Card></div>
  </>;
}

function TeamListItem({ team }: { team: Team }) { return <Link to={`/admin/teams/${team.id}`} className="team-list-item"><span className="team-list-color" style={{background:team.color}}/><div className="team-list-info"><div className="team-list-name">{team.name}</div><div className="team-list-meta">{team.memberCount} members · {team.leadCount} leads</div></div><div className="team-list-value"><div className="team-list-revenue">{formatCurrency(team.revenue)}</div><div className={team.growth < 0 ? "team-list-growth down" : "team-list-growth"}>{team.growth > 0 ? "+" : ""}{team.growth}%</div></div><ChevronRight size={14} color="var(--charcoal-300)"/></Link>; }
function PageIntro({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode }) { return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-description">{description}</p></div>{actions && <div className="page-actions">{actions}</div>}</div>; }
